### ISSUE TITLE
Deleted queues got recreated on server crash

### ISSUE THREAD

**Issue by oskgu360** [cloudamqp/avalanchemq#209]
Seen on:  v1.0.0-alpha.22 
What happened:
1. queue got created through amqpcat
2. queue got manually deleted through UI 
3. Server crashed due to GC error (Maybe restart does it aswell?)
4. On startup queue got recreated

Jan 20 13:54:46 <server>[59652]: vhost=****** queue=testqueue: (messages=0) Deleted
Jan 20 14:58:48 <server> [66463]: vhost=****** queue=testqueue: Restoring index
Jan 20 14:58:48 <server> [66463]: vhost=****** queue=testqueue: 0 messages

**Comment by carlhoerberg** [comment]
The problem is that the queue is already deleted here: 
https://github.com/cloudamqp/avalanchemq/blob/9e22b6ca4107c83e33e3fd7197f8135cb3d7c3f8/src/avalanchemq/vhost.cr#L619 So it can't check if the queue was durable or not  :facepalm: . Working on a fix
