### ISSUE TITLE
Use GitHub releases

### ISSUE THREAD

**Issue by dentarg** [cloudamqp/avalanchemq#226]
We can use https://github.com/marketplace/actions/create-a-release

Upside: "Releases" are more prominent displayed in the GitHub UI (e.g. in the side bar on the repo front page https://github.com/cloudamqp/avalanchemq)

_Originally posted by @carlhoerberg in https://github.com/cloudamqp/avalanchemq/issues/219#issuecomment-765814287_

**Comment by carlhoerberg** [comment]
Or delete all existing releases? And then the github repos main page will just says "123 tags", instead of showing an old release.

**Comment by dentarg** [comment]
We could, but I think we should embrace releases :) We are embracing issues and discussions, so using releases makes sense to me!

**Comment by carlhoerberg** [comment]
I don't get how to use the annotated tag message as body for the release, and others seems to have the same problem too: https://github.com/actions/create-release/issues/118

**Comment by carlhoerberg** [comment]
And `git show` doesn't respect the `--format` flag when the ref is a tag some some reason

**Comment by carlhoerberg** [comment]
but maybe `git show -s v1.0.0-alpha.25 | tail -n+6` could work

**Comment by dentarg** [comment]
@carlhoerberg what about `git tag -l -n99 v1.0.0-alpha.25`?

```
$ git tag -l -n99 v1.0.0-alpha.25
v1.0.0-alpha.25 1.0.0-alpha.25

    - Deleted queues could reappear after a crash
    - Never send frames to closed channels
    - Checking RSS on OS X could fail when FD limit was reached
    - Escaping connection name in UI to prevent XSS
    - Crystal 0.36.0 compability
    - Don't open a temp write for every channel, only when needed

```

Found it in https://stackoverflow.com/questions/5358336/how-to-list-all-tags-along-with-the-full-message-in-git

**Comment by dentarg** [comment]
Could also do (I'm sure there's a clever way to remove the PGP block)

```
$ git tag --list --format="%(body)" v1.0.0-alpha.25
- Deleted queues could reappear after a crash
- Never send frames to closed channels
- Checking RSS on OS X could fail when FD limit was reached
- Escaping connection name in UI to prevent XSS
- Crystal 0.36.0 compability
- Don't open a temp write for every channel, only when needed
-----BEGIN PGP SIGNATURE-----

iQIzBAABCAAdFiEEMzD4srPR52lwwLOiPeQ7a6E9BckFAmAVeyUACgkQPeQ7a6E9
BckjoA//YSm1LUI9DbxLo2qcjLPqz1P+HAIsIdsCoEmH4jH0Qui16ydT/XMZ9fZZ
O5/5SGewOmQgI/m1IOvtXvRyhpWwaxMB35tbiY7zFOXZCvuuG3YatIWFMvhGZ4h6
dgdgHiFXC4QRbNqRKEN5wVep+prCN0vfnBAFJVpEcH8rWAb+lZO/yyK2QrsW/HDJ
wo4Zch1P4Ya6S/s5NG8+QbQifTkkaVeTRjPU6ovrrlJ2GIQYd35Mzd7/2MoZEIaF
Y5MwnWuc0Nt5uBWmBZWAUqb2OH98KeY77uOSg2awhK0p1MztQ6d85AGhwgTARsGi
paxhICUsfzyyDhxdfQaUossydKHrxrPyjQwffRdNeW50GIDjO2s3I2UU6z0WsUgz
lMi6CA2GJbW3kAq3RV0JhI2SSnpNxcy+yR9NFUDfzOuqrSAWOCUHt8augqu2Oly+
Kg0XAX4c4B8BkGgIpX64+uELGusM3ESQ93BSMy/4rV7A5kPbzMHbtY6qpTh7XRTn
dWtTACQraoPLJ/JneS52i+JNoS0+Akpi/MkGrEDIlzD9orshZhpmKFnTXk6rIUve
jNWUSZ58OTr5UAXWHUkZVhxfN+kfm530yvVtJEC9AfiLQ4n4QmoFWRfpB6o7K1gC
YVQIvY5nPQszbOAGgNNtpDTsoC1HOuvCI1lY6vomY6N1CYnxGwA=
=9rTq
-----END PGP SIGNATURE-----
```
