### ISSUE TITLE
Upgrade to a more recent version of Chart.js

### ISSUE THREAD

**Issue by carlhoerberg** [cloudamqp/avalanchemq#248]
We're currently using a version from 2018.

**Comment by dentarg** [comment]
Chart.js was updated to https://github.com/chartjs/Chart.js/releases/tag/v2.9.4 in https://github.com/cloudamqp/avalanchemq/commit/a8c83ffc5d458d672758be35ec78a4752151332c (and package.json files updated in https://github.com/cloudamqp/avalanchemq/commit/67827c5e3beca48931114cc2ae897d0cd2349cae)
