### ISSUE TITLE
Handle poison messages

### ISSUE THREAD

**Issue by snichme** [cloudamqp/avalanchemq#256]
Similar to https://www.rabbitmq.com/quorum-queues.html#poison-message-handling: if a messages has been redelivered x-times, remove it

**Comment by antondalgren** [comment]
Already implemented: https://github.com/cloudamqp/avalanchemq/blob/7a40a994075fb4c67c7ec30996b85a1791c8e7fa/spec/server_spec.cr#L771-L787
