### ISSUE TITLE
Improve wrong shovel configuration feedback

### ISSUE THREAD

**Issue by johanrhodin** [cloudamqp/avalanchemq#313]
1. Create a shovel with incorrect auth parameters.
2. It will display in management as `Stopped`. That is not very helpful.
3. It will log the correct reason:
```
Nov 30 19:38:34 test-cold-pony-01 avalanchemq[3793]: vhost=ncwcmkiw shovel=mulitplicatorshovel: 403 - ACCESS_REFUSED
Nov 30 19:38:39 test-cold-pony-01 avalanchemq[3793]: amqpserver client=127.0.0.1:44184: User "rwftbixn" not found
```

`Access refused` or `User not found` would be a better error message

**Comment by tbroden84** [comment]
Just tried and add additional state (AccessRefused) and check the exception to catch the 403 error. This can then easily be displayed as state information in the ui. 

![Screenshot 2022-03-01 at 13 25 27](https://user-images.githubusercontent.com/47317658/156169278-bd4016a1-f896-4d6b-adc2-a5ca5d512ca9.png)

Or should we instad use a more generic error state (Error) and present additional information found in the error field in the response body? E.g. also catch other exceptions

`2022-03-01 13:01:26 +01:00 [ERROR] vhost=cloudamqp shovel=test: Error connecting to '127.0.0.1:5544': Connection refused (AMQP::Client::Error)`

**Comment by jage** [comment]
> Or should we instad use a more generic error state (Error) and present additional information found in the error field in the response body? E.g. also catch other exceptions

I think that would be really neat to see the real issue here, instead of having to dig through logs.
