### ISSUE TITLE
Add AMQP 1.0 support

### ISSUE THREAD

**Issue by dragosv** [cloudamqp/avalanchemq#322]
AMQP 1.0 is the standard and there many servers that support it (RabbitMQ supports with through a plugin). AvalanceMq should support it either by setting the version or through a plugin.

**Comment by jage** [comment]
Are you using AMQP 1.0 today, is there anything stopping you from using 0.9.1 @dragosv? 

Not on the roadmap, and as Carl said, it's a different protocol and not a logical next version of the same protocol.
Will close this, but we're happy to hear more about your use-case for future planning.

**Comment by dragosv** [comment]
Want to have the flexibility to use multiple cloud providers if I need Enterprise support (if I want to switch from AvalancheMq to Azure, [Azure Service Bus](https://azure.microsoft.com/en-us/services/service-bus/) supports only the AMQP 1.0 version). Only [Amazon MQ](https://aws.amazon.com/amazon-mq/) supports both 1.0 and 0.9.1 versions of the protocol.

**Comment by dentarg** [comment]
If you are looking for a managed service, we do offer RabbitMQ in multiple clouds: https://www.cloudamqp.com/
